from .ce_loss import CELoss
from .hard_triplet_loss import HardTripletLoss
from .kl_loss import KLLoss
from .lifted_structure_loss import LiftedStructureLoss
from .precision_at_topk_loss import PrecisionAtTopkLoss
from .proxy_nca_loss import ProxyNCALoss
from .sigmoid_focal_loss import SigmoidFocalLoss
from .softmax_focal_loss import SoftmaxFocalLoss
from .triplet_margin_loss import TripletMarginLoss
from .online_triplet_margin_loss import OnlineTripletMarginLoss
from .multi_similarity_loss import MultiSimilarityLoss
from .circle_loss import CircleLoss
from .smooth_ap_loss import SmoothAPLoss
